# Generated by Django 5.2.10 on 2026-02-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_alter_status_nama_status_rename_category_kategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='id_produk',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
